#ifndef SPA_EQUALITY_OPERATOR_H
#define SPA_EQUALITY_OPERATOR_H

enum EqualityOperator {
  EQUALS,
  NOT_EQUALS,
  GREATER_THAN,
  GREATER_THAN_OR_EQUALS,
  LESSER_THAN,
  LESSER_THAN_OR_EQUALS,
};

#endif  // SPA_EQUALITY_OPERATOR_H
