//
// Created by Josiah Khoo on 25/8/22.
//

#ifndef SPA_TIMES_DIVIDE_QUOTIENT_OPERATOR_H
#define SPA_TIMES_DIVIDE_QUOTIENT_OPERATOR_H

enum TimesDivideQuotientOperator { TIMES, DIVIDE, QUOTIENT };

#endif // SPA_TIMES_DIVIDE_QUOTIENT_OPERATOR_H
