name: cmake-windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        build-type: [ Release ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Project
        run: |
          cd Team03/Code03
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --target unit_testing --config ${{matrix.build-type}}
          cmake --build . --target integration_testing --config ${{matrix.build-type}}
          cmake --build . --target autotester --config ${{matrix.build-type}}
          cd ../..

      - name: Run unit tests
        run: ./Team03/Code03/build/src/unit_testing/${{matrix.build-type}}/unit_testing.exe

      - name: Run integration tests
        env:
          SAMPLE_SOURCE_PATH: ${{github.workspace}}\\Team03\\Tests03\\Sample_source.txt
          TEST_FOLDER: ${{github.workspace}}\\Team03\\Tests03
          OS: win

        run: ./Team03/Code03/build/src/integration_testing/${{matrix.build-type}}/integration_testing.exe

      - name: Run automated autotester tests
        run: python autoautotester.py --autotester_path ./Team03/Code03/build/src/autotester/${{matrix.build-type}}/autotester.exe --test_dir ./Team03/Tests03 --os windows
