name: test-clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: './Team03/Code03/src/spa/src ./Team03/Code03/src/unit_testing/src'
          extensions: 'h,cpp'
          clangFormatVersion: 14
          style: google